from ConversationsCleaning.cleaner import start_cleaning as conversation_cleaning
from ADS_Manager.ads_manager import check_ads_posts
from Dynamic_title_vk.dynamic_title_manager import update_title_vk
from vk_birthday_manager.vk_birthday_manager import send_happy_birthday
